name: CI
  

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  test:
    name: "${{ matrix.os }} :: ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    defaults:
    run:
      shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-22.04,windows-latest,macos-latest]

        python-version: [3.11]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        python-version: ${{ matrix.python-version }}

    - name: install dash bio
      run: |
        conda install conda-forge::dash-bio
    
    
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install -r requirements-dev.txt


    - name: Install prerelease version of pymip (only for macos arm64)
      if: matrix.os == 'macos-latest'
      run: |
        python -m pip install -U pip
        pip install mip==1.16rc0
        
    - name: Run pytest
     
      run: |
        cd script_maker2000
        python -m pytest -v -s
   